name: Terraform Deployment
on: [push]

permissions:
  contents: read
  id-token: write

jobs: 
    deploy:
        runs-on: ubuntu-latest
        defaults: 
            run: 
                working-directory: ./terraform
        steps:
            - uses: actions/checkout@v3
            - name: Fetch keys from vault
              uses: hashicorp/vault-action@v3
              with:
                  url: http://54.167.68.205:8200
                  role: gh-actions-role
                  method: jwt
                  secrets: |
                      aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID;
                      aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY;

            - uses: hashicorp/setup-terraform@v2
            - run: terraform init
            - run: terraform plan
            - run: terraform apply -auto-approve